---
title: "Lab2"
author: "Gani Agadilov"
date: "2/20/2019"
output: pdf_document
---

```{r}
library(ggplot2)
library(sf)
library(ggspatial)

p <- ggplot() +
  geom_sf(data = read_sf("data/ME-GIS/Coastline2.shp"), 
          colour="grey10", fill="grey90") +
  geom_sf(data = read_sf("data/ME-GIS/Rivers19.shp"), 
          colour="steelblue", size=0.3) +
  geom_sf(data = read_sf("data/ME-GIS/PrimaryRoads.shp"), 
          size = 0.7, colour="grey30") +
  geom_sf(data = read_sf("data/ME-GIS/Cities.shp")) +
  theme_bw()

p + geom_sf_text(data = read_sf("data/ME-GIS/Cities.shp"),aes(label = Name))+annotation_scale(location = "bl")+ annotation_north_arrow(which_north = "true", location ="tl")

```

```{r}
library(ggplot2)
library(maps)
states <- map_data("state")
head(states)

library(dplyr)
michigan <- 
  states %>% 
  filter(region=="michigan") %>%
  group_by(group) %>% 
  summarize(
    region = region[1],
    n = n())
michigan

ggplot(states, aes(x=long, y=lat, group=group)) + geom_polygon()
```

```{r}

ozbig <- read_sf("gadm36_AUS_shp/gadm36_AUS_1.shp")
oz_st <- maptools::thinnedSpatialPoly(
  as(ozbig, "Spatial"), tolerance = 0.1, 
  minarea = 0.001, topologyPreserve = TRUE)
oz <- st_as_sf(oz_st)
oz

is.list(oz$geometry)

str(oz$geometry[[1]])

head(oz$geometry[[1]][[3]][[1]])


```